- name: Intro
  hosts: all

  tasks:
  - name: Tmount
    ansible.posix.mount:
      path: /dev/shm
      src:  tmpfs
      fstype: tmpfs
      opts:  defaults,nodev,nosuid,noexec
      state: present

  - name: set SELINUX correct
    ansible.builtin.lineinfile:
      path: /etc/selinux/config
      line: SELINUX=permissive  
      create: no  
      regexp: SELINUX=.*
