- name: Intro
  hosts: all



  tasks:
  - name: Tmount
    ansible.posix.mount:
      path: /dev/shm
      src:  tmpfs
      fstype: tmpfs
      opts:  defaults,nodev,nosuid,noexec
      state: present

  - name: set SELINUX correct
    ansible.builtin.lineinfile:
      path: /etc/selinux/config
      line: SELINUX=permissive  
      create: no  
      regexp: SELINUX=.*

  - name: Check Premesion
    ansible.builtin.file:
      path: /etc/issue
      state: file
      mode: '0644'
      owner: root
      group: root

  - name: Install chrony
    ansible.builtin.package:
      name: "{{ item }}"
      state: present  
    loop: "{{ packages }}"
    tags:
      - mojsze
      - tomek

  - name: cron enable
    ansible.builtin.systemd:
      name: crond
      enabled: yes
    tags:
      - mojsze

  - name: set sshd
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      line: PermitEmptyPasswords no  
      create: no  
      regexp: PermitEmptyPasswords.*
    tags:
      - sshd
    notify:
      - restart_ssh

  handlers:
  - name: restart_ssh
    ansible.builtin.systemd:
      name: sshd
      state: restarted




#
##  - name: Install iptables
##    ansible.builtin.package:
#      name: iptables
#      state: present  