---
# tasks file for upjenkins
- name: Download jenkins
  get_url:
    url: "https://get.jenkins.io/war-stable/{{ jenkins_version }}/jenkins.war"
    dest: /var/tmp/jenkins.war
    mode: '0440'
    checksum: "sha256:https://get.jenkins.io/war-stable/{{ jenkins_version }}/jenkins.war.sha256"
  
  when: ansible_facts["architecture"] == "aarch64"